// Payment Network (Layer 2) abstraction — v0.6 groundwork only.
//
// In v0.7 we want tunnel rentals (and any future provider rentals) to
// settle through xssnick/ton-payment-network virtual channels rather
// than per-tx onchain payments. To avoid a refactor when that lands we
// thread a payment-aware seam through the daemon spawn / connect path
// now, returning a no-op implementation in v0.6.
//
// References:
//   https://github.com/xssnick/ton-payment-network
//   https://github.com/ton-blockchain/adnl-tunnel  (PaymentsClientConfig)

export interface PaymentNetworkClient {
  /** Whether this client will actually settle anything onchain/offchain. */
  readonly enabled: boolean

  /**
   * Return the wallet/secret material the daemon should embed in its
   * tonutils config under TunnelConfig.Payments. Returns null when
   * payments are disabled — caller must omit the section in that case.
   */
  describePayments(): null | {
    paymentsNodeKeyB64: string
    walletPrivateKeyB64: string
    minVirtualChannelBalanceTon: string  // decimal string, e.g. "0.05"
  }

  /**
   * Best-effort one-line status for CLI output. Implementations should
   * not block — synchronous, formatted summary only.
   */
  status(): string
}

/**
 * No-op client used in v0.6. Returns enabled=false everywhere; the
 * tonutils backend writes only the default ed25519 keys generated by
 * adnl-tunnel/config and leaves PaymentsEnabled=false in config.json.
 */
export const noopPaymentClient: PaymentNetworkClient = {
  enabled: false,
  describePayments: () => null,
  status: () => 'payments: disabled (v0.7)',
}

// Future shape sketch — DO NOT IMPORT FROM RUNTIME YET (v0.6 only ships
// the noop). When v0.7 lands, replace `noopPaymentClient` with a real
// implementation that wraps a spawned `ton-payment-network` node and
// reads its onchain channel state.
//
//   export class TonPaymentClient implements PaymentNetworkClient {
//     constructor(opts: { wallet: KeyPair, ... })
//     enabled = true
//     describePayments() { return { ... real material ... } }
//     status() { return `payments: TON Payment Network, balance=…` }
//   }
